# the base image
FROM python:3.7-slim-stretch

# node user/uid/gid must matches the host system in order to properly access shared folder in container.
ARG user=xicheng
ARG user_uid=1003
ARG user_gid=1003
ENV notebook_dir=$notebook_dir

RUN set -ex; groupadd -g $user_gid $user  && \
    useradd -m -g $user_gid -s /bin/bash -d /home/$user -u $user_uid $user  

# upload a list of useful Debian packages when developing codes
COPY packages.lst /root/

# install packages based on the above list
RUN set -ex; apt-get update && \
    mkdir -p /usr/share/man/man1 && \
    sed '/^ *#/d' /root/packages.lst | xargs apt-get install -y --no-install-recommends --no-install-suggests  && \
    rm -rf /var/lib/apt/lists/*

# upload a list of Python modules
COPY modules.lst /root/

# install the python modules based on the above list
RUN set -ex ; \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /root/modules.lst --upgrade --upgrade-strategy only-if-needed && \
    rm -rf ~/.cache

# copy entrypoint.sh
COPY ./docker-entrypoint.sh /usr/local/bin/

# set up container user to run the program
USER $user

# set jupyter notebook as entrypoint, use port:9999 
ENTRYPOINT /usr/local/bin/docker-entrypoint.sh "$notebook_dir"

# default command to execute at run time
CMD [ "/bin/bash" ]

