version: '3.2'

services:
  python3: 
    image: xc_python3:xauth
    build: 
      context: ./
      dockerfile: Dockerfile-xauth
      args:
        user: ${USER:-xicheng}
        user_uid: ${USER_UID:-1003}
        user_gid: ${USER_GID:-1003}
    hostname: xc_py3
    networks:
      xcnet:
    working_dir: /shared
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${SHARED:-./}:/shared:z"
      - "./home:/home/${USER}:z"
      - "/tmp/.X11-unix:/tmp/.X11-unix:z"
    restart: always
    tty: true
  redis:
    image: redis:4
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "xc_redis_data:/data"
      - "./redis.conf:/usr/local/etc/redis.conf:ro"
    networks:
      xcnet:
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis.conf" ]
  mysql:
    image: xc_mysql:5.7
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    env_file:
      - ./mysql.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./mysql.init.d:/docker-entrypoint-initdb.d:ro"
      - "./mysql.conf.d:/etc/mysql/mysql.conf.d:ro"
      - "xc_mysql_data:/var/lib/mysql"
    networks:
      xcnet:
    restart: always
networks:
  xcnet:
volumes:
  xc_mysql_data:
  xc_redis_data:
