FROM mysql:5.7

COPY ./mysql_init.sql /docker-entrypoint-initdb.d/

# add programs that's useful to run mysql, i.e. `less`
RUN set -ex; \
    apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests less && \
    rm -rf /var/lib/apt/lists/*

# default command to run
CMD ["mysqld"]
