version: '3.2'

services:
  python3: 
    image: 'xc_python3:master'
    build: 
      context: ./
      dockerfile: Dockerfile-master
      args:
        user: ${USER:-xicheng}
        user_uid: ${USER_UID:-1003}
        user_gid: ${USER_GID:-1003}
    hostname: amityville
    networks:
      xcnet:
    ports:
      - "127.0.0.1:9999:9999"
    working_dir: /shared
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix:z"
      - "${SHARED:-./}:/shared:z"
      - "./home:/home/${USER}:z"
      - "/data/hdfs/spark-latest:/data/spark:ro"
    environment:
      - "notebook_dir=/shared"
    restart: always
  redis:
    image: 'redis:4'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "xc_redis_data:/data"
      - "./redis.conf:/usr/local/etc/redis.conf:z"
    networks:
      xcnet:
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis.conf" ]
  mysql:
    image: 'xc_mysql:5.7'
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    hostname: xc_mysql
    env_file:
      - ./mysql.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./mysql.init.d:/docker-entrypoint-initdb.d:z"
      - "./mysql.conf.d:/etc/mysql/mysql.conf.d:z"
      - "xc_mysql_data:/var/lib/mysql"
    networks:
      xcnet:
    restart: always
  mongo:
    image: 'mongo:3.4'
    hostname: elmont
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "xc_mongo_data:/data/db"
      - "./mongod_config.yml:/data/configdb/mongod.yml:z"
    networks:
      xcnet:
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    command: [ "/usr/bin/mongod", "-f", "/data/configdb/mongod.yml" ]
networks:
  xcnet:
volumes:
  xc_mysql_data:
  xc_redis_data:
  xc_mongo_data:
